### PR TITLE
Migrate schedule creation inputs and buttons to tbpro components

### LINKED ISSUE #460: "No Confirmation Needed" or "Confirmation Needed"
I like to confirm meeting times, but some people may not need to. We should expose an option in the short-term (and in the long-term expose this in onboarding) to be able to turn off confirmation (or we could choose to make that the default and have a "Confirmation Needed" option that you turn on). So that folks can allow people to grab time on their calendars instantly with no confirmation required.

### PR DESCRIPTION
**Pull request by devmount**
## Description of the Change

This change migrates text inputs, selects, primary buttons and secondary buttons to use tbpro components.

## Benefits

One step further to the new design.

## Applicable Issues

Implements #460

### CODE REVIEW

**Comment by MelissaAutumn** [comment]
Looks good, but missed one 😄 

image

**Review by MelissaAutumn — APPROVED** [review]

**Comment by devmount** [comment]
@MelissaAutumn Yeah, this is kind of a special field and the tbpro text-input does not really fit in here... 😅 

image

But I can extend it to be "invisible" (without borders or background).

**Comment by MelissaAutumn** [comment]
That would probably work foe now

**Comment by devmount** [comment]
I removed the background for now:
image

**Pull request merged**
