### PR TITLE
Components elements subdirectories TypeScript

### PR DESCRIPTION
**Pull request by devmount**
## Description of the Change

This change adds types for all Vue components in `elements/**/*`. For further typing, the previous PRs need to be merged first (hence there are some Todos in this PR).

Also the script section was moved to the top in most of the vue files.

## Applicable Issues

Implements #413

### CODE REVIEW

**Review by MelissaAutumn — COMMENTED** [review]
Looks good, but I don't see any additional typing? Was that a missed commit, or did I read this PR wrong.

**Comment by devmount** [comment]
Yes, I add types as soon as the previous PRs get merged in another PR (that's why there are some TODO comments added here)

**Review by devmount — COMMENTED** [review]
@MelissaAutumn I added the types now 😅 I decided to move the props types into a separate interface, let me know your thoughts on this. If you prefer to do type-based declaration of the props, I can change that. From this PR on, I will do it consistently for all further components.

**Review by MelissaAutumn — APPROVED** [review]
Looks good, Thanks!

**Pull request merged**
