### PR TITLE
feat: Upgrade Backend Python to 3.12

### PR DESCRIPTION
**Pull request by Mr-Sunglasses**
## Description of the Change

Upgrade the Backend Python version to 3.12

## Benefits

Upgrading to Python 3.12 brings performance improvements and other bug fix.

## Applicable Issues

fix: #637

### CODE REVIEW

**Comment by Mr-Sunglasses** [comment]
Hey @MelissaAutumn,  I've upgrade to py3.12, but haven't change the prod dockerfile, do let me know that if I've change the py version in that also.

**Review by MelissaAutumn — APPROVED** [review]
Thank you for the contribution! 

Automated tests look green, and works fine locally.

**Comment by ryanleesipes** [comment]
Thanks for the contribution @Mr-Sunglasses !

**Comment by Mr-Sunglasses** [comment]
Thanks @ryanleesipes @MelissaAutumn , looking forward to contribute more to the project 😃

**Comment by devmount** [comment]
@Mr-Sunglasses That's awesome! Thanks so much!

**Pull request merged**
