### PR TITLE
Password Login Fixes

### PR DESCRIPTION
**Pull request by MelissaAutumn**
Part of #120 

This allows the password flow to create a new subscriber on first-login. But only first-login. (Well when there's no subscribers.) 

Input wanted: Do we need to put this behaviour behind a env flag for extra security? 

I discovered a fun bug with schedule creation/updates that causes it to fail because times are in UTC and 14:00 as a start-time is bigger than 0:00 as an end time. So we now collect timezones for schedules, and store them. (That'll be handy later!) We don't do anything else with them right now.

### CODE REVIEW

**Comment by malini** [comment]
+1 for hiding this behind an env flag! Best to isolate this behaviour from prod as much as possible

**Comment by MelissaAutumn** [comment]
> +1 for hiding this behind an env flag! Best to isolate this behaviour from prod as much as possible

Sounds good, it's only active with password auth and not fxa as that will always create new users.

**Comment by MelissaAutumn** [comment]
And added the env gate.

**Review by devmount — APPROVED** [review]
Tested this and looks like it works without any issues! Thank you!

**Pull request merged**
